package com.company.compiler.shijak;

import com.company.compiler.common.token.IdentifierToken;
import com.company.compiler.common.token.IgnoredToken;
import com.company.compiler.common.token.Token;

public class ShijakTokens {
    public static Token nameToken = new IdentifierToken("[a-zA-Z_]+[a-zA-Z_0-9]*");
    public static Token intConstToken = new Token("-?[0-9]+");
    public static Token floatConstToken = new Token("-?[0-9]+\\.[0-9]+");
    public static Token charConstToken = new Token("'.'");
    public static Token trueConstToken = new Token("true");
    public static Token falseConstToken = new Token("false");
    public static Token openingBracketToken = new Token("\\(");
    public static Token closingBracketToken = new Token("\\)");
    public static Token openingCurlyBracketToken = new Token("\\{");
    public static Token closingCurlyBracketToken = new Token("}");
    public static Token openingSquareBracketToken = new Token("\\[");
    public static Token closingSquareBracketToken = new Token("]");
    public static Token expressionCombinerToken = new Token(">>");
    public static Token functionToken = new Token("fun");
    public static Token bagToken = new Token("bag");
    public static Token defineToken = new Token("define");
    public static Token ifToken = new Token("if");
    public static Token elifToken = new Token("elif");
    public static Token elseToken = new Token("else");
    public static Token whileToken = new Token("while");
    public static Token breakToken = new Token("break");
    public static Token continueToken = new Token("continue");
    public static Token outputToken = new Token("output");
    public static Token inputToken = new Token("input");
    public static Token letToken = new Token("let");
    public static Token allocToken = new Token("alloc");
    public static Token fillToken = new Token("fill");
    public static Token freeToken = new Token("free");
    public static Token eqToken = new Token("eq");
    public static Token inToken = new Token("in");
    public static Token semiColonToken = new Token(";");
    public static Token commaToken = new Token(",");
    public static Token dotToken = new Token("\\.");
    public static Token colonToken = new Token(":");
    public static Token plusToken = new Token("\\+");
    public static Token minusToken = new Token("-");
    public static Token equalToken = new Token("==");
    public static Token notEqualToken = new Token("!=");
    public static Token lessThanToken = new Token("<");
    public static Token greaterThanToken = new Token(">");
    public static Token lessThanOrEqualToken = new Token("<=");
    public static Token greaterThanOrEqualToken = new Token(">=");
    public static Token multiplicationToken = new Token("\\*");
    public static Token divisionToken = new Token("/");
    public static Token moduloToken = new Token("%");
    public static Token notToken = new Token("!");
    public static Token andToken = new Token("&&");
    public static Token orToken = new Token("\\|\\|");
    public static Token intToken = new Token("int");
    public static Token floatToken = new Token("float");
    public static Token boolToken = new Token("bool");
    public static Token charToken = new Token("char");
    public static Token voidToken = new Token("void");
    public static Token returnToken = new Token("return");
    public static Token blankToken = new IgnoredToken("[ \t]*");
    public static Token newLineToken = new IgnoredToken("\n");
}
